src/View/Admin/WooTab.php

[CC-110](https://webdevstudios.atlassian.net/browse/CC-110)

CC-110: Remove call to nonexistent method enqueue_scripts

---

package-lock.json
package.json

Ran updates for outdated dependencies, including major updates

CC-120: Build Tools Updates

---

CODEOWNERS

Title says it all.
See [CC-127](https://webdevstudios.atlassian.net/browse/CC-127) for more information.

CC-127 Remove CODEOWNERS from CC-Woo

---

package-lock.json
package.json

[CC-124](https://webdevstudios.atlassian.net/browse/CC-124)
Update dependencies

CC-124: NPM Security Alerts

---

README.txt
package-lock.json
package.json
plugin.php
src/Plugin.php

Prep for 1.3.0 release.
Drop build number so `1.3.0-1` becomes `1.3.0`
Add 1.3.0 changes to README.txt Changelog

Chore - Prep for 1.3.0 release

---

README.txt

Ticket: [CC-130](https://webdevstudios.atlassian.net/browse/CC-130)
Updates readme per client request.
Nothing to test, other than to ensure the readme update matches the client criteria:
> Add: " Automatically send a customized branded abandoned cart email to customers who left items in their cart and track resulting revenue "
At the bottom of the section "With Constant Contact you can:"

CC-130: Update Readme

---

README.txt

[CC-144](https://webdevstudios.atlassian.net/browse/CC-144)
Add documentation links to CTCT-Woo readme file for easier access for users.
Added the links in the FAQ section of readme.txt (similar to how it was handled in CC-Forms).

CC-144 Update readme.txt to add documentation links

---

README.txt
src/Settings/SettingsValidator.php
src/View/Admin/WooTab.php

Merge sprint/20.05 to master for release
[CC-144](https://webdevstudios.atlassian.net/browse/CC-144) Add documentation links to CTCT-Woo readme file for easier access for users.
[CC-145](https://webdevstudios.atlassian.net/browse/CC-145) Revise and better test phone number validation in CTCT-Woo plugin.

Merge sprint/20.05 to master for release

---

README.txt
package.json
plugin.php
src/Plugin.php

Update PLUGIN_VERSION constant to 1.3.2
Update Version header field to 1.3.2
Update package.json version number to 1.3.2
Update README.txt Stable tag field to 1.3.2
Add 1.3.2 changes to README.txt Changelog

Chore/prep release 1.3.2

---

src/Rest/AbandonedCheckouts/Schema.php
src/View/Admin/MenuItem.php

Ticket: [CC-174](https://webdevstudios.atlassian.net/browse/CC-174)
Addressed i18n-related linting errors as outlined in ticket.

CC-174: Address i18n linting errors

---

src/AbandonedCheckouts/CheckoutHandler.php
src/Api/RequestHandler.php
src/Meta/ConnectionStatus.php
src/Rest/AbandonedCheckouts/Controller.php
src/Rest/AbandonedCheckouts/Schema.php
src/Settings/SettingsModel.php
src/Utility/Validatable.php
src/View/Checkout/CampaignId.php
src/View/Checkout/NewsletterPreferenceCheckbox.php
src/View/ViewRegistrar.php

Ticket: [CC-176](https://webdevstudios.atlassian.net/browse/CC-176)
Addresses misc linting errors/warnings (all remaining except prefixing errors).
Note: PR against `sprint/20.07`, as that branch holds the rest of the linting fixes and has not been merged to `master` yet.

CC-176: Address misc linting errors

---

plugin.php
src/Api/KeyManager.php
src/Plugin.php
src/View/Admin/WooTab.php
uninstall.php

Ticket: [CC-186](https://webdevstudios.atlassian.net/browse/CC-186)
Addresses prefix mismatch errors (functions, hooks, variables).
- Standardized prefix for CC Woo is `cc_woo` w/ text-domain `cc-woo`.
Adds hook comments.

CC-186: Address prefix errors

---

README.txt
package.json
plugin.php
src/Plugin.php

- Resolving various undefined index notices when `WP_DEBUG` is enabled.
- Adding minimum required WooCommerce version.

prep release 1.3.3

---

src/View/Admin/WooTab.php

Ticket: https://webdevstudios.atlassian.net/browse/CC-243
Added support to make login URL overrideable.

Added support for dynamic login url.

---

.distignore
.github/workflows/deploy.yml

Ticket: https://webdevstudios.atlassian.net/browse/CC-258

Action for Auto-deploy

---

README.txt
package-lock.json
package.json
plugin.php
src/Plugin.php

Prep Release 1.4.0

---

src/View/Admin/WooTab.php

Updated the connection on CC Woo to save and connect to CC at once. 
https://webdevstudios.atlassian.net/browse/CC-318
The connection flow is upgraded and other design changes and tab changes will be handled on CC-317. If this feature is 
1. Install on a vanilla WP.
2. See that you can connect to CTCT if you save and fill in those details.

CC :: 318 :: Update the connection flow

---

README.txt
plugin.php

Chore/prep release 2.0.0

---

.distignore
composer.json

- Changed the file list for proper deploy action. 
- Removed composer command for zip deploy.

Proper files list for the deploy action. 

---

.distignore
.gitignore
README.txt
composer.json
package.json
plugin.php
src/Plugin.php

Minor release following the 2.0.0 release with some bug fixes giving out PHP notices and some deployment changes.

Release :: 2.0.1

---

README.txt
app/admin.css
package.json
plugin.php
src/Plugin.php
src/View/Admin/MenuItem.php

There were some reports of design conflicts with WP core on the current version. This release fixes those issues. 
ref: https://wordpress.org/support/topic/admin-css-cause-problemas-in-customize-screen/

fixed :: Design conflict with WP Core

---

src/View/Admin/WooTab.php
src/View/Admin/connected.php

update URLs to match new destinations. White space

---

src/AbandonedCheckouts/CheckoutHandler.php

Added to be included with abandoned cart requests
https://webdevstudios.atlassian.net/browse/CC-339

add address information to "checkout_contents" column

---

src/AbandonedCheckouts/CheckoutHandler.php

remove deprecated address fields

---

package-lock.json
package.json

update our package dependencies

---

src/AbandonedCheckouts/CheckoutHandler.php
src/AbandonedCheckouts/CheckoutRecovery.php
src/Utility/NonceVerification.php
src/View/Admin/WooTab.php
src/View/Admin/connected.php
src/View/Admin/welcome.php
src/View/Checkout/CampaignId.php

remove instances of FILTER_SANITIZE_STRING for PHP8 compatibility

---

src/Settings/SettingsModel.php

add our checkbox setting to our settings model

---

README.txt
composer.json
package.json
plugin.php
src/Plugin.php
src/Utility/HealthPanel.php

Release 2.2.0

---

composer.json
composer.lock
phpcs.xml.dist
plugin.php

Reverts WebDevStudios/constant-contact-woocommerce#184

Revert "Release221"

---

README.txt
composer.lock
package.json
plugin.php
src/Plugin.php

Release221

---

README.txt
composer.json
composer.lock
package-lock.json
package.json
phpcs.xml.dist
plugin.php

This PR handles nuts and bolts package updates and can be considered as compatible with WP 6.5.
We're not running new builds of the files, as we're not changing anything with those, so should have no issue with the build files.

Release222

---

README.txt
package-lock.json
package.json
plugin.php
src/Plugin.php
src/Utility/AdminNotifications.php
src/Utility/CheckoutBlockNewsletter.php

This PR merges in all previously reviewed and approved PRs.
1. Fixing issues around customer opt-in with the checkout block.
2. Adding prompts regarding pending available updates to our own plugin.

Merge in version 2.3.1 bugfix release

---

README.txt
package.json
plugin.php
src/AbandonedCheckouts/CheckoutRecovery.php
src/Plugin.php

All the changes so far for a version 2.3.2 bugfix release.

Changes for version 2.3.2 bugfix
