src/AbandonedCheckouts/CheckoutRecovery.php

Ticket: [CC-121](https://webdevstudios.atlassian.net/browse/CC-121)
- Removes old unused `recover_customer_info` method from `CheckoutRecovery`.
- Adds functionality (and new method `maybe_recover_checkout_email`) to recover saved checkout user email IF the current site user is a guest (not logged in) AND they have not set an email in the current session.
1. Create abandoned checkout (add items and at least enter an email address at checkout).
2. Either clear browser cache/session or open incognito browser.
3. Recover checkout: `<local_domain>/?recover-checkout=<checkout_uuid>` - `<checkout_uuid>` can be obtained from the db.
4. Go to checkout page and confirm email from original checkout is preserved.
5. Repeat steps 1, 3, 4 from another window that already has a checkout created (i.e., …

CC-121: Abandoned Checkouts are not preserving the email address when returning to Cart

---

src/View/Admin/WooTab.php

[CC-110](https://webdevstudios.atlassian.net/browse/CC-110) work was done during the 20.01 sprint, and PR'ed against the [sprint/20.01](https://github.com/WebDevStudios/constant-contact-woocommerce/commits/sprint/20.01) branch in #86.
However, the [sprint/20.01](https://github.com/WebDevStudios/constant-contact-woocommerce/commits/sprint/20.01) branch was never merged to master, as we did not do a release in January, and we are now in 20.03 sprint (but still using 20.02 branch).
[sprint/20.02](https://github.com/WebDevStudios/constant-contact-woocommerce/commits/sprint/20.02) branched off of master, without this work, leaving this orphaned on [sprint/20.01](https://github.com/WebDevStudios/constant-contact-woocommerce/commits/sprint/20.01).
We could merge …

Merge CC-110 work into sprint 20.02 so it doesn't get lost

---

README.txt
package.json
plugin.php
src/AbandonedCheckouts/CheckoutHandler.php
src/AbandonedCheckouts/CheckoutRecovery.php
src/Plugin.php
src/Rest/AbandonedCheckouts/Controller.php

Per the email we received today, going with targeted release version of `1.3.0`.
Checkout method's `@since` tags will use `1.3.0` since that's the target release number.
Everything else updated to version-build `1.3.0-1` for the QA team's parser.

Chore/increment version to 1.3.0-1

---

README.txt
plugin.php

As noted in [CC-125](https://webdevstudios.atlassian.net/browse/CC-125), WooCommerce was unable to determine what version of Woo we declare support for, as the "WC tested up to" tag was in the wrong place, it does not belong in the README.txt, but in the plugin header.
Before:
After:

CC-125 Move the 'WC tested up to' tag from README.txt to plugin.php

---

README.txt
plugin.php

Bump `WC tested up to` to `4.0.1`
Bump `WP Tested up to` to `5.4.0` (Tested with RC3 on Lab)

CC-126: Test CC-Woo against latest WordPress and WooCommerce versions

---

src/View/Checkout/CampaignId.php
src/View/Checkout/NewsletterPreferenceCheckbox.php

Ticket: [CC-64](https://webdevstudios.atlassian.net/browse/CC-64)
Updates instances of `add_post_meta()` to `$order->update_meta_data` and changes corresponding hooks to `woocommerce_checkout_create_order` (as that hook passes the full `WC_Order` object instead of just `$order_id`).
Place and order and confirm `cc_woo_customer_agrees_to_marketing` is added to the order metadata if "Sign me up to receive marketing emails (optional)" is selected at checkout.

CC-64: Update instances of `add_post_meta`

---

README.txt
package.json
plugin.php
src/Plugin.php
src/View/Checkout/CampaignId.php
src/View/Checkout/NewsletterPreferenceCheckbox.php

Replace `@since NEXT` with `@since 1.3.1`
Increment PLUGIN_VERSION constant to 1.3.1
Increment Version in plugin header to 1.3.1
Increment Stable tag in README.txt to 1.3.1
Increment version in package.json to 1.3.1
Add 1.3.1 to Changelog in README.txt

Chore/prep release 1.3.1

---

src/Settings/SettingsValidator.php
src/View/Admin/WooTab.php

More details added to ticket [CC-145](https://webdevstudios.atlassian.net/browse/CC-145).
Updated PR...
Use WooCommerce WC_Validation::is_phone() rather than homespun regex
has_valid_phone should return false if phone number is empty
Use WooCommerce wc_sanitize_phone_number() rather than homespun regex
Do not redirect to customer_data_import screen if we don't meet requirements

CC-145 Use WC_Validation::is_phone() rather than homespun regex

---

src/View/Admin/WooTab.php

The wc_sanitize_phone_number function has only been available since WC 3.6.0.
Saw at least one support forum user running WC 3.4.2.

CC-145 Provide fallback if wc_sanitize_phone_number isn't available

---

plugin.php

[CC-161](https://webdevstudios.atlassian.net/browse/CC-161)
Adds `WC requires at least: 3.6.0` to plugin header.

CC-161: Add WC min version to plugin header

---

src/View/Admin/WooTab.php

Ticket: [CC-172](https://webdevstudios.atlassian.net/browse/CC-172)
Adds fallback for potentially undefined array indices.
Note: I couldn't get the "Undefined index" warnings to display on my local before implementing the potential fix, so I can't say 100% they're gone. @tw2113 if you know how to trigger them, let me know and I can test again.

CC-172: Address undefined index notices

---

src/View/Admin/WooTab.php

Ticket: [CC-188](https://webdevstudios.atlassian.net/browse/CC-188)
Adds ID attr to admin field definition.
1. Confirm message field below "Import your contacts" now shows complete ID attribute in source for WC > Constant Contact settings page.

CC-188: Add ID attr to admin setting field

---

src/View/Admin/WooTab.php
src/View/Checkout/NewsletterPreferenceCheckbox.php

Ticket: https://webdevstudios.atlassian.net/browse/CC-223
Description: Adds setting to change where opt-in location is displayed to now choose between the `woocommerce_after_checkout_billing_form` or `woocommerce_review_order_before_submit` hook.

Added support to change opt-in location.

---

src/Plugin.php

Since there was no other way to use HTTP instead of HTTPS on sites that don't have SSL enabled, I've added a notice to make sure they enable SSL before they connect to CTCT WOO plugin. 
This happens due to wrong protocol return from the Authorization url or middleware which forces the use of SSL.
https://webdevstudios.atlassian.net/browse/CC-313?atlOrigin=eyJpIjoiY2I5ODdkYjgzNDRjNGYzMmE1Mzc2Y2ZhODIxNTU1MzgiLCJwIjoiaiJ9

CC - 313 :: Notfiy about the SSL requirement 

---

src/Plugin.php

We have a PHP warning from the plugin when SSL is not present on the site that came with a faulty check when notice was added for sites not having SSL.
https://webdevstudios.atlassian.net/browse/CC-325

FIX :: check if SSL is present on the server.

---

composer.json

The plugin removes the PHPCS XML file when a zip file for release is created with composer for some reason. This PR removes that but also makes sure that the file is not present on the release zip. 
https://webdevstudios.atlassian.net/browse/CC-327

fix::added phpcs xml file to exclude list on composer archive.

---

webpack.config.js

On 2.0.0 I added multiple entries for WebPack was was not building the old frontend js files. Fortunately no changes were made on those files so we have no issues on the current live version. 
This PR fixes the WebPack entries and builds into respective files. 
Creating this PR to Main instead of a release branch since we might need it for development for the next release.

Fixed :: WebPack not building files correctly. 

---

plugin.php

Hooks in to WC's system to mark plugins as compatible or incompatible with "High Performance Order Storage" which we don't do anything with, so we are good to mark as compatible.

declare compatibility with HPOS

---

src/AbandonedCheckouts/CheckoutHandler.php

Prevents running `save_checkout_data()` too frequently and when away from the checkout page, for the callback on the `woocommerce_cart_updated` hook.
See https://webdevstudios.atlassian.net/browse/CC-430

run this save checkout only when in checkout

---

src/Utility/AdminNotifications.php

This PR adds a new admin notification if the correct conditions are met and if the plugin is currently outdated compared to what's available on WordPress.org.
This is similar to the PR we have for the Forms plugin to do the same thing: https://github.com/WebDevStudios/constant-contact-forms/pull/674
See https://webdevstudios.atlassian.net/browse/CC-427

new code for admin notifications regarding plugin updates being available

---

README.txt
plugin.php
src/Api/KeyManager.php
src/Plugin.php
src/Utility/WebhookAPICleanup.php
src/View/Admin/Disconnect.php
tests/phpunit/Api/KeyManagerTest.php

This PR merges in all the changes regarding version 2.4.0.
Version 2.4.0 is going to add support for clearing out existing created webhooks as well as API connections upon CTCT Woo deactivation process. This will clean up those tables.
It also corrects one method name to not have a space in "woocommerce"

Release 2.4.0
